version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: demodrf_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5434:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - POSTGRES_DB=demodrf_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - DATABASE_URL=postgres://admin:admin123@db:5432/demodrf_db
    stdin_open: true
    tty: true

volumes:
  postgres_data:
