# -*- coding: utf-8 -*-
"""Zillow Api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fby2MfupB2ob5NaM5Dlz4J8rmf1YF_yy
"""


import pandas as pd
import random

def mock_fetch_price(address, valid_addresses):
    if address not in valid_addresses:
        return 50000
    return round(random.uniform(250000, 1000000), 2)

def update_with_mock_prices(df):
    actual_prices = []
    discounted_prices = []

    valid_addresses = df['Property Address'].tolist()

    for address in df['Property Address']:
        actual_price = mock_fetch_price(address, valid_addresses)
        actual_prices.append(actual_price)
        # Apply 39.3% discount
        discounted_price = round(actual_price * 0.607, 2)
        discounted_prices.append(discounted_price)

    df.insert(df.columns.get_loc('Property Address') + 1, 'Actual Price', actual_prices)
    df.insert(df.columns.get_loc('Actual Price') + 1, 'Discounted Price', discounted_prices)

    return df

file_path = 'API 1 Home.xlsx'
df = pd.read_excel(file_path)
pd.set_option('display.max_columns', None)

print(df.head())

df = update_with_mock_prices(df)

output_file_path = 'updated_properties_with_prices.xlsx'
try:
    df.to_excel(output_file_path, index=False, engine='openpyxl')
    print(f"Updated file saved successfully as {output_file_path}")
except Exception as e:
    print(f"Error saving the file: {e}")

print(df)